### PR TITLE
Add audio spectrum (FHT) mode

### PR DESCRIPTION
**Pull request by PaintYourDragon**
This adds a new device type configuration: CONFIG_FHT, which generates a live audio spectrum via FHT algorithm.
Things to know:
- FHT is ONLY supported on MEGATINYCORE devices right now (e.g. ATtiny 816/817).
- If CONFIG_FHT is enabled, NO OTHER Seesaw modes can be supported by the device. No GPIO, no ADC, no NeoPixel. Flash is full. RAM is full. Everything is full.
- This depends on the Open Music Labs FHT library, which is NOT available in the Arduino Library manager and must be done manually. Might be relevant to CI.
- Even with other Seesaw modes disabled, this required _some measures_ to fit in RAM. Some globals were eliminated (made local as they didn’t really need permanence) and/or downsized (there’s only a 3 byte I2C buffer if FHT is enabled…this is both the minimum needed for configuration and requests, and the maximum possible with ATtiny816/817 RAM…even _one_ byte larger and it collapses like a soufflé).
- Regarding last item, I tested a couple of the other modes to confirm they still work, but this was not an extensive survey of every mode and device, as I don’t have hardware here. While nothing jumps out as likely-to-break, I can’t guarantee that.
- F_CPU on an FHT-enabled Seesaw device would ideally be 10 MHz for 3.3V operation, or 20 MHz for 5V. Other rates are permissible, but final documentation with meaningful numbers will require knowing what was ultimately selected here.

### CODE REVIEW

**Comment by PaintYourDragon** [comment]
Some additional notes on the changes made, in case anything here jumps out as “don’t do that”:
- In Adafruit_seesawPeripheral.cpp, comment out the Serial.print() call, leaving foo() as an empty function. Otherwise won't fit on ATtiny817. Since this appears to be a nonsense .cpp file to get the Arduino compiler to acknowledge the .h files here, I don’t think this change actually affects anyone (other than making the resulting executable smaller, if Serial debug isn’t used).
- in Adafruit_seesawPeripheral_main.h, Adafruit_seesawPeripheral_pinChangeDetect() is only declared if CONFIG_INTERRUPT is set to 1, and function is called only if that is set and USE_PINCHANGE_INTERRUPT is 0. This eliminates 8 bytes worth of global variables if CONFIG_INTERRUPT isn’t used, and is required to fit the FHT-related code into ATtiny816/817 RAM.
As many of these changes are specifically to fit FHT on 816/817, reverting _any_ of these will require moving up to a 1616/1617 part. It’s literally right at the limit. _Might_ be able to free up one extra byte.

**Comment by ladyada** [comment]
ok please fix compilation error and also lets just use the 1617 - so update the CI to add a 1617 test plz!

**Comment by PaintYourDragon** [comment]
Compilation won’t work until corresponding change in Adafruit_Seesaw is merged. Shall I go ahead and do that? I was being super extra cautious and waiting for review first. That one _does_ pass CI with the changes.

**Comment by ladyada** [comment]
ok merged, you'll need to do a release

**Pull request merged**
