### PR TITLE
pins should not require IRQ enable for encoder support

### PR DESCRIPTION
**Pull request by ladyada**
the previous code required us enablign interrupts on the pins, that isnt necessary - we should be checking any encoder pins!

### CODE REVIEW

**Comment by caternuson** [comment]
Is the goal here to remove the encoder pin checking from `Adafruit_seesawPeripheral_pinChangeDetect()` and outside of any `#if CONFIG_INTERRUPT` blocks?

**Comment by ladyada** [comment]
yeah encoders should piggyback on the 'gpio interrupt' code but they are not the same thing

**Comment by caternuson** [comment]
@ladyada oops. hadn't forgot about this. figured maybe we were waiting for the BSP issue to get resolved?

one thing i noticed was possible typo here:
```cpp
#if CONFIG_ENCODER
    encoder_mask |= ENCODER0_INPUT_MASK;
#ifdef ENCODER1_INPUT_MASK
    mask |= ENCODER1_INPUT_MASK;
#endif
#ifdef ENCODER2_INPUT_MASK
    mask |= ENCODER2_INPUT_MASK;
#endif
#ifdef ENCODER3_INPUT_MASK
    mask |= ENCODER3_INPUT_MASK;
#endif
```

`mask` instead of `encoder_mask` inside the other preproc conditionals.

**Comment by ladyada** [comment]
i fixed in the next PR!

**Pull request merged**
